### ISSUE TITLE
running KASM Stand Alone + Nginx Proxy Manager+ Authentik

### ISSUE THREAD

**Issue by moutasem1989** [kasmtech/workspaces-images#116]
I am interested in running [Desktop ](https://hub.docker.com/r/kasmweb/desktop) as a Stand Alone Web Service but i suppose they all function more ore less the same. I made this Docker Compose to try and spin it up:
```
services:
  kasmweb:
    image: kasmweb/desktop:1.16.0
    container_name: kasmweb
    ports:
        - 6901:6901
    stdin_open: true
    tty: true
    shm_size: '2gb'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/dri:/dev/dri
    env_file: /dockerfiles/kasmweb.env
    networks:
      - public

networks:
  public:
    external: true
```
It does run with errors related to being in Stand Alone and not connected to KASM Workspace. One Environment variable they mention in the [documentation ](https://hub.docker.com/r/kasmweb/desktop)is `VNC_PW=password` which in turn is used in Basic HTTP Authentication i assume:
```
User : kasm_user
Password: password
```
Going to `https://<ip>:6901` will get you to the Desktop GUI in your browser and it will work smoothly.

![image](https://github.com/user-attachments/assets/b32741aa-f520-4420-924b-8e6f6fd742ca)

Because I like to secure my services even when used to test software I disabled the ports so the service is accessed only through NPM and enable Websockets for the Proxy Host. You will get again to the HTTP Authentication but even with correct cridentials it will error out:
```
 2024-10-17 10:41:04,174 [INFO] websocket 8: got client connection from 172.19.0.15
 2024-10-17 10:41:04,186 [DEBUG] websocket 8: using SSL socket
 2024-10-17 10:41:04,195 [DEBUG] websocket 8: X-Forwarded-For ip '192.168.20.59'
 2024-10-17 10:41:04,195 [INFO] websocket 8: Authentication attempt failed, BasicAuth required, but client didn't send any
 2024-10-17 10:41:04,195 [INFO] websocket 8: 172.19.0.15 192.168.20.59 - "GET / HTTP/1.1" 401 158
 2024-10-17 10:41:04,195 [DEBUG] websocket 8: No connection after handshake
 2024-10-17 10:41:04,195 [DEBUG] websocket 8: handler exit
```
For some reason NPM is not forwarding the cridentials to the KASM Host.
Despite that I did try setting up a Reverse Proxy Authentication in Authentik and tried setting up Basic HTTP Authentication:

![image](https://github.com/user-attachments/assets/c89bfc4f-dd0b-4caf-97c0-a99a3dd936d9)

Note that `proxy_pass http://authentik.company:9000/ `should be changed accordingly for the NPM setup. 
According to this [Websockets issue](https://github.com/goauthentik/authentik/issues/3637) adding this to the NPM configuration is needed:
```
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```
or:
```
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_http_version 1.1;
```
However neither did work for me.

How can I put KASM Service behind Nginx Proxy Manager and allow HTTP Basic Authentication to work?
If does not work, Can Basic HTTP Authentication be disabled?
How can I use Authentik reverse proxy authentication with KASM websockets and Basic HTTP Authentication on NPM?
