### ISSUE TITLE
Steam doesn't display correctly

### ISSUE THREAD

**Issue by deviantintegral** [kasmtech/workspaces-images#87]
Hello!

Thanks for providing these images. I'm using kasmvnc directly over at https://github.com/deviantintegral/ddev-playwright and I was excited to see a Steam image available!

My goal isn't to play games, but just to run steam to act as a local cache for installing games on a steam deck. Since it can't download games while asleep (even plugged in!), it's very handy to have a computer do bigger downloads first, and then the deck can grab updates quickly over the LAN.

What's happening is a little odd. I can connect and see steam update, and I was able to log in. However, steam itself isn't rendering correctly.

Here it is working during updating:

<img width="2168" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/255023/d791bd35-b089-4863-a8d7-360b350a8074">

And logging in:

<img width="2168" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/255023/b39d0d94-4dff-460b-b286-12ffa3a429a6">

But we can see the main app window isn't rendering right:

<img width="2168" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/255023/db6385c4-7eb9-4623-a11c-5c4bf0546b11">

And if I hover over a menu, it shows up:

<img width="2168" alt="image" src="https://github.com/kasmtech/workspaces-images/assets/255023/530f4d28-bbcc-4f8e-9b5d-adf920202955">

I also noticed there's no xfce toolbar or the like - is that expected?

I can run `xterm` and it shows up, but I can't drag the window around.

Any ideas?

Here's my docker-compose.yaml file.

```yaml
version: '3'
services:
  steam-headless:
    image: kasmweb/steam:1.14.0
    restart: unless-stopped
    shm_size: 512m
    ports:
      - 6901:6901
    environment:
      - VNC_PW=password

    volumes:
      - home:/home/kasm-user:rw
      - /main/steam-games/:/mnt/steam-games:rw
networks:
  default:
    external: true
    name: services
volumes:
  home:
```

And logs: https://gist.github.com/deviantintegral/29c27083e914a6640d26ba44aaf20b24
